[detectors]
# Exclude test files from Wake analysis
exclude_paths = [
    "test/**/*.sol",
    "test/**/*.t.sol"
]

[compiler]
# Solidity compiler settings
solc_remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[paths]
# Source paths
sources = ["src"]
# Exclude test directory from analysis
exclude = ["test"]